local module = {
	["/cmds"] = { -- Admin Panel
		desc = "Opens GUI menu",
		noBtn = true,
		order = 1,
		cmdType = "cmds"
	},
	["/give (player) (amount) (item name)"] = { -- Give items to players
		desc = "Give players items",
		plrGui = true,
		cmdType = "give",
		createlist = "itemsOnly",
		order = 2,
	},
	["/remove (player) (amount) (item name)"] = { -- Remove items from players
		desc = "Remove items from players",
		plrGui = true,
		cmdType = "remove",
		createlist = "plrinv",
		order = 3,
	},
	["/kill (player)"] = { -- Kill players
		desc = "Kill players",
		plrGui = true,
		cmdType = "kill",
		order = 4,
	},
	["/fly (player)"] = { -- Fly players
		desc = "Make players Fly, NEEDS DISABLED ANTICHEAT/ANTIHACK!",
		plrGui = true,
		cmdType = "kill",
		order = 28,
	},
	["/freeze (player)"] = { -- Freeze players, For moderation, Kinda broken, needs fix in V2
		desc = "Freeze or unfreeze players",
		plrGui = true,
		cmdType = "freeze",
		order = 5,
	},
	["/kick (player) (reason)"] = { -- Kick players
		desc = "Kick players >:)",
		plrGui = true,
		quick = true,
		cmdType = "kick",
		order = 6,
	},
	["/tp (player) (player)"] = { -- Teleport players to each other
		desc = "Teleport players :o",
		plrGui = true,
		cmdType = "tp",
		createlist = "players",
		order = 7,
	},
	["/setcoins (player) (amount)"] = { -- Set coin amount
		desc = "Set coin amount",
		plrGui = true,
		quick = true,
		cmdType = "setcoins",
		order = 8,
	},
	["/addcoins (player) (amount)"] = { -- Add coin amount
		desc = "Add coin amount",
		plrGui = true,
		cmdType = "addcoins",
		quick = true,
		order = 9,
	},
	["/setmelons (player) (amount)"] = { -- Set volleyball amount/ Melon Amount
		desc = "Set volleyball amount",
		plrGui = true,
		quick = true,
		cmdType = "setmelons",
		order = 8,
	},
	["/addmelons (player) (amount)"] = { -- Add volleyball amount/ Melon Amount
		desc = "Add volleyball amount",
		plrGui = true,
		cmdType = "addmelons",
		quick = true,
		order = 9,
	},
	["/setmojo (player) (amount)"] = { -- Set mojo amount
		desc = "Set mojo amount",
		plrGui = true,
		cmdType = "setmojo",
		quick = true,
		order = 10,
	},
	["/addmojo (player) (amount)"] = { -- Add mojo amount
		desc = "Add mojo amount",
		plrGui = true,
		cmdType = "addmojo",
		quick = true,
		order = 11,
	},
	["/addexp (player) (amount)"] = { -- Add exp/Essence amount, Kinda broken since it adds into current level instead of onto, needs fix in V2
		desc = "Add exp amount",
		plrGui = true,
		cmdType = "addexp",
		quick = true,
		order = 12,
	},
	["/setexp (player) (amount)"] = { -- Add exp/Essence amount
		desc = "Set exp amount",
		plrGui = true,
		cmdType = "setexp",
		quick = true,
		order = 13,
	},
	["/setlvl (player) (amount)"] = { -- Set lvl amount
		desc = "Set lvl amount",
		plrGui = true,
		cmdType = "setlvl",
		quick = true,
		order = 16,
	},
	["/setspell (player) (spell name)"] = { -- Set player's Voodoo / Aether Voodoo spell
		desc = "Set player's spell",
		plrGui = true,
		cmdType = "setspell",
		createlist = "voodoospells",
		order = 17,
	},
	["/setvoodoo (player) (amount)"] = { -- Set player Voodoo Energy Amount
		desc = "Set player's voodoo to a specific number",
		plrGui = true,
		cmdType = "setvoodoo",
		quick = true,
		order = 18,
	},
	["/cosmetic (player) (cosmetic)"] = { -- Give player cosmetics, Kinda broken, works like 2/3 times, Needs fix in V2
		desc = "Give players cosmetics",
		plrGui = true,
		cmdType = "cosmetic",
		createlist = "cosmeticlist",
		order = 19,
	},
	["/mojo (player) (mojo)"] = { -- Give player a specific Mojo Perk/Recipe
		desc = "Give player a mojo perk",
		plrGui = true,
		cmdType = "mojo",
		createlist = "mojolist",
		order = 20,
	},
	["/customrecipe (player) (recipe name)"] = { -- Give player a custom recipe, LARGELY DEPRECATED
		desc = "Give players your custom recipes",
		plrGui = true,
		cmdType = "customrecipe",
		quick = true,
		order = 21,
	},
	["/an (text)"] = { -- Make an annoucement
		desc = "Make an annoucement",
		cmdType = "annouce",
		textbox = true,
		order = 22,
	},
	["/reset (plr)"] = { -- Reset Item, Stats and Level Savedata
		desc = "Reset player stats",
		plrGui = true,
		cmdType = "reset",
		order = 23,
	},
	["/clear (plr)"] = { -- Clear player invetory
		desc = "Clear player invetory",
		plrGui = true,
		cmdType = "clear",
		order = 24,
	},
	["/suspend (plr)"] = { -- Suspend a player for 7 days, Kinda Broken on some versions since it needs the unban GUI to work, Working on a fix tho prolly wont come until V3
		desc = "Suspend a player for 7 days",
		plrGui = true,
		cmdType = "suspend",
		quick = true,
		order = 25,
	},
	["/shutdown"] = { -- Shutdown Current Server
		desc = "Shutdown Server",
		cmdType = "shutdown",
		startup = true,
		order = 26,
	},
	["/shutdownall"] = { -- Shutdown ALL servers in universe
		desc = "Shutdown All Servers",
		cmdType = "shutdownall",
		startup = true,
		order = 27,
	},
}

return module]]></ProtectedString>
					<string name="ScriptGuid">{f439772c-2602-4038-9cdd-a51f4a9b6634}